name: swapp CI/CD pipeline

on:
  push:
    branches: [ never ]
  pull_request:
    branches: [ never ]

jobs:
  redeployment:
    runs-on: [ self-hosted, internal, docker ]

    steps:
    - uses: actions/checkout@v2
    - name: Redeploy docker container (makefile chain target)
      run: make run

#  import_data:
#    runs-on: [ self-hosted, internal, docker ]
#    needs: [ redeployment ]

#    steps:
#    - uses: actions/checkout@v2
#    - name: Import static data to production
#      run: make import_prod_static_data
